[build]
  command = "npm install --legacy-peer-deps && npm install style-loader css-loader less-loader less --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  COREPACK_ENABLE = "0"